### ISSUE TITLE
Graph/visual - in upper right section on PAC pages

### ISSUE THREAD

**Issue by ngrad** [sunlightlabs/read_FEC#101]

**Comment by jsfenfen** [comment]
This should probably be many different tickets--there are different graphs on different pages. Specifically I'd say there are graphs on the right upper section on PAC and candidate pages. There could be one on district pages, it would have to displace the map (or not).

**Comment by ngrad** [comment]
Gotcha - adding cards now

**Comment by boblannon** [comment]
planning to refactor dryrub to make more IE charts available to realtime.  see sunlightlabs/dryrub#3
