### ISSUE TITLE
dryrub static files need update

### ISSUE THREAD

**Issue by boblannon** [sunlightlabs/read_FEC#103]
not sure how these got out of step, but, for instance, the background of the nav needs to be updated:

http://realtime.influenceexplorer.com/static/dryrub/images/nav_bg.jpg

vs.

http://influenceexplorer.com/static/dryrub/images/nav_bg.jpg

**Comment by apendleton** [comment]
These hash bit-for-bit identical, so I don't think this is a thing.

**Comment by boblannon** [comment]
my b.  local caching issue
