### ISSUE TITLE
Use the ribbon nav thingy

### ISSUE THREAD

**Issue by jsfenfen** [sunlightlabs/read_FEC#44]
This would help nav, but would be a ton of template work, since everything has been built without it and assumes wider width. Can the ribbon just go over stuff instead of to the left of it?

**Comment by boblannon** [comment]
andrew, when you have time, can you comment on feasibility?

**Comment by apendleton** [comment]
I don't think it going over stuff would work well from a usability perspective. You'd effectively lose a chunk of usable screen real estate the height of the ribbon and the width of the whole display, as you'd have to scroll the whole thing down to be able to see what was under the ribbon, and there might be some content at the bottom of the page that you couldn't get to be visible at all. So yes, if we were going to do it, the content would have to be made narrower. Not worth it, in my opinion.

**Comment by boblannon** [comment]
okay, yeah, since it appears that the ribbon depends on the newer, CBV-based view and template setup in brisket, we'll go forward with something else.  see #104 for more.
