### ISSUE TITLE
Remove search

### ISSUE THREAD

**Issue by ngrad** [sunlightlabs/read_FEC#99]

**Comment by jsfenfen** [comment]
So it's easy enough to override the search block -- it's in dryrub here: https://github.com/sunlightlabs/dryrub/blob/master/dryrub/templates/dryrub/base.html#L69 -- it's really a question of what the page looks like if one does. But I think this is more of a dryrub thing.

**Comment by jsfenfen** [comment]
Closed in b3d3f13058471e4c61e6e295b35f3ce418b633e4
